preprocessing:
  expression_gene_id_col_name: 'TargetID'
  mapping_gene_id_col_name: 'GENE_ID'
  genotype_snp_id_col_name: 'SNP'
  mapping_snp_id_col_name: 'SNP_ID'
  align:
  split:
    test_size: 0.2

structure_learning:
  pairwise_inference:

  network_inference:
    fdr_prior: 0.6
    network_type: p
  featurize:

modeling:
  train: 
    learning_rate: 0.01
    num_iterations: 10000
    weight_prior_std: 1
    cross_val_split: 5
    random_state: 8927
    input_type: eqtl
    model_type: lasso
    feature_selection:
      number_of_features: 10
  evaluate:
